// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What switching off an autostart entry did.
 */
export type AutostartDisabledDto = { what: string, 
/**
 * How to put it back, for the one location with no reversible option.
 */
restoreHint: string | null, };
