// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A known fan controller arranged to start with this machine.
 *
 * Reported separately from a *running* application because the two need different
 * answers. A running rival is a fight happening now; an autostart entry is a fight
 * scheduled for the next reboot, on a machine nobody will be watching.
 */
export type AutostartEntryDto = { 
/**
 * Index into the service's current survey, used to act on this entry.
 */
id: number, 
/**
 * Stable key, e.g. `fancontrol`.
 */
key: string, name: string, 
/**
 * Where it lives, phrased for someone who did not put it there.
 */
location: string, 
/**
 * The command it runs.
 */
command: string, 
/**
 * Whether switching it off can be undone without our help.
 */
reversible: boolean, };
