// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fan's measured duty-to-speed relationship, brought across from another tool.
 */
export type CalibrationDto = { channel: string, label: string, 
/**
 * `[duty percent, rpm]` pairs, ascending by duty.
 */
points: Array<[number, number]>, 
/**
 * The lowest duty at which the fan was seen turning.
 */
lowestTurningDuty: number | null, 
/**
 * Whether the table actually contains a stall, rather than merely not reaching
 * one. A table that never read zero is not proof that low duties are safe.
 */
foundTheStall: boolean, };
