// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is driving an output channel, for the takeover panel.
 *
 * Mirrors [`of_hal::ChannelControl`]. `Unknown` means the backend could not tell, which
 * the interface must never render as "fine".
 */
export type ChannelControlDto = "firmware" | "ours" | "foreign" | "unknown";
