// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An output channel the active backend can drive.
 */
export type ChannelDto = { id: string, label: string, 
/**
 * The tachometer that reads this channel back, when one is wired to it.
 */
tachometer: string | null, 
/**
 * Lowest duty the device reliably spins at, once known.
 */
minReliableDuty: number | null, };
