// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One option in a choice parameter.
 */
export type ChoiceOption = { 
/**
 * The serialized value, exactly as the document stores it.
 */
value: string, label: string, };
