// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a comparator's output relates to its threshold.
 */
export type Compare = "above" | "below";
