// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Another application that is running and what it means for us.
 */
export type ContendingAppDto = { 
/**
 * Stable key, e.g. `fancontrol`.
 */
key: string, name: string, processName: string, pid: number, 
/**
 * `controller`, `monitor` or `vendor`.
 */
role: string, 
/**
 * Plain-language explanation shown next to it.
 */
note: string, 
/**
 * Whether it has to stand down before we can drive a fan.
 */
mustStop: boolean, };
