// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelControlEntry } from "./ChannelControlEntry";
import type { ContendingAppDto } from "./ContendingAppDto";

/**
 * Everything the takeover panel needs to explain the situation.
 */
export type ContentionReport = { channels: Array<ChannelControlEntry>, apps: Array<ContendingAppDto>, 
/**
 * Channels under foreign manual control — nothing is responding to temperature
 * on these.
 */
stranded: Array<string>, 
/**
 * True when nothing needs doing.
 */
clear: boolean, 
/**
 * Why a takeover cannot proceed right now, if it cannot.
 */
blocker: string | null, };
