// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRef } from "./PortRef";

/**
 * A typed connection from one node's output to another node's input.
 */
export type Edge = { from: PortRef, to: PortRef, };
