// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configuration file belonging to another fan controller.
 */
export type ForeignConfigDto = { 
/**
 * Stable key of the application it belongs to.
 */
key: string, name: string, path: string, 
/**
 * How it was found, so a user can tell a live configuration from an old backup.
 */
foundVia: string, };
