// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { NodeId } from "./NodeId";
import type { NodeInstance } from "./NodeInstance";

/**
 * An editable fan-control graph. May be invalid; call [`Graph::validate`] to find out.
 */
export type Graph = { nodes: { [key in NodeId]: NodeInstance }, edges: Array<Edge>, };
