// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelDto } from "./ChannelDto";
import type { SensorDto } from "./SensorDto";

/**
 * What the backend can see on this machine.
 */
export type HardwareInventory = { backend: string, sensors: Array<SensorDto>, channels: Array<ChannelDto>, 
/**
 * True when kernel-level hardware access is available.
 */
driverPresent: boolean, 
/**
 * A sentence the UI can show verbatim when it is not.
 */
driverSummary: string, };
