// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalibrationDto } from "./CalibrationDto";
import type { Graph } from "./Graph";
import type { ImportNoteDto } from "./ImportNoteDto";

/**
 * A translated configuration, for review. **Importing does not apply it.**
 */
export type ImportedProfileDto = { name: string, graph: Graph, notes: Array<ImportNoteDto>, calibration: Array<CalibrationDto>, 
/**
 * True when nothing at all could be translated.
 */
empty: boolean, };
