// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing an import did, or declined to do.
 */
export type ImportNoteDto = { 
/**
 * `exact`, `approximated`, `needs-attention` or `skipped`.
 */
fidelity: string, subject: string, detail: string, };
