// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutostartEntryDto } from "./AutostartEntryDto";
import type { ContentionReport } from "./ContentionReport";
import type { ForeignConfigDto } from "./ForeignConfigDto";

/**
 * Everything OpenFan knows about the other fan-control software on this machine.
 *
 * The three states a new installation can be in, answered in one place: nothing else
 * here, something installed but idle, or something running right now.
 */
export type MigrationSurvey = { 
/**
 * Rivals running at this moment, and what else holds the bus.
 */
contention: ContentionReport, 
/**
 * Rivals that will start with the machine.
 */
autostart: Array<AutostartEntryDto>, 
/**
 * Configurations found on disk that could be imported.
 */
configs: Array<ForeignConfigDto>, 
/**
 * True when no other fan-control software is running, scheduled to run, or
 * installed — the clean-machine case.
 */
nothingElseHere: boolean, };
