// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a mixer combines its inputs.
 */
export type MixMode = "max" | "min" | "average" | "sum";
