// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the palette groups a node.
 */
export type NodeCategory = "source" | "transform" | "stateful" | "logic" | "sink";
