// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeCategory } from "./NodeCategory";
import type { NodeKind } from "./NodeKind";
import type { PortDto } from "./PortDto";

/**
 * A node kind the editor can offer in its palette.
 *
 * `template` is a complete, immediately-valid [`NodeKind`], so adding a node from the
 * palette never produces a half-configured node the backend would reject.
 */
export type NodeDescriptor = { 
/**
 * Stable discriminator, matching the serde tag of [`NodeKind`].
 */
kind: string, label: string, category: NodeCategory, 
/**
 * One line explaining what the node is for.
 */
description: string, template: NodeKind, inputs: Array<PortDto>, outputs: Array<PortDto>, };
