// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

/**
 * A node instance: its kind (which carries the node's parameters) plus editor metadata.
 */
export type NodeInstance = { kind: NodeKind, 
/**
 * User-visible name. Falls back to the kind's default label when empty.
 */
label: string, 
/**
 * Canvas position. Carried through so the backend owns the whole document and the
 * UI stays a pure view of it.
 */
position: [number, number], };
