// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compare } from "./Compare";
import type { CurvePoint } from "./CurvePoint";
import type { MixMode } from "./MixMode";
import type { Quantity } from "./Quantity";

/**
 * A node's kind and its parameters.
 *
 * Note how few variants carry a `quantity`: the generic ones infer it, so there is no
 * type to set and no way to set one inconsistently with what it is wired to.
 */
export type NodeKind = { "kind": "sensor", sensor_id: string, quantity: Quantity, } | { "kind": "constant", value: number, } | { "kind": "curve", points: Array<CurvePoint>, } | { "kind": "mix", mode: MixMode, } | { "kind": "clamp", min: number, max: number, } | { "kind": "offset", delta: number, } | { "kind": "scale", factor: number, } | { "kind": "reinterpret", from: Quantity, to: Quantity, } | { "kind": "rate-limit", max_delta_per_second: number, } | { "kind": "low-pass", tau_seconds: number, } | { "kind": "moving-average", samples: number, } | { "kind": "hold", band: number, } | { "kind": "comparator", threshold: number, deadband: number, direction: Compare, } | { "kind": "select" } | { "kind": "pid", setpoint: number, kp: number, ki: number, kd: number, 
/**
 * Bound on the integral's contribution, in duty percent.
 */
integral_limit: number, } | { "kind": "fan-output", channel: string, };
