// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compare } from "./Compare";
import type { CurvePoint } from "./CurvePoint";
import type { MixMode } from "./MixMode";
import type { Quantity } from "./Quantity";

/**
 * A node's kind and its parameters.
 */
export type NodeKind = { "kind": "sensor", sensor_id: string, quantity: Quantity, } | { "kind": "constant", quantity: Quantity, value: number, } | { "kind": "curve", input: Quantity, points: Array<CurvePoint>, } | { "kind": "mix", quantity: Quantity, mode: MixMode, } | { "kind": "clamp", quantity: Quantity, min: number, max: number, } | { "kind": "offset", quantity: Quantity, delta: number, } | { "kind": "scale", quantity: Quantity, factor: number, } | { "kind": "reinterpret", from: Quantity, to: Quantity, } | { "kind": "rate-limit", quantity: Quantity, max_delta_per_second: number, } | { "kind": "low-pass", quantity: Quantity, tau_seconds: number, } | { "kind": "moving-average", quantity: Quantity, samples: number, } | { "kind": "hold", quantity: Quantity, band: number, } | { "kind": "comparator", quantity: Quantity, threshold: number, deadband: number, direction: Compare, } | { "kind": "select", quantity: Quantity, } | { "kind": "pid", quantity: Quantity, setpoint: number, kp: number, ki: number, kd: number, 
/**
 * Bound on the integral's contribution, in duty percent.
 */
integral_limit: number, } | { "kind": "fan-output", channel: string, };
