// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a numeric parameter is measured in.
 *
 * Several parameters are denominated in whatever the node's own `quantity` is set to —
 * a Hold band on a temperature is degrees, on a duty is percent. Those resolve in the
 * editor against the live value rather than being frozen into a fixed string here.
 */
export type ParamUnit = { "unit": "none" } | { "unit": "fixed", symbol: string, } | { "unit": "quantity" } | { "unit": "quantity-rate" };
