// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOption } from "./ChoiceOption";
import type { ParamUnit } from "./ParamUnit";

/**
 * How a parameter should be edited.
 */
export type ParamKind = { "type": "number", min: number | null, max: number | null, step: number, unit: ParamUnit, } | { "type": "integer", min: number | null, max: number | null, } | { "type": "quantity" } | { "type": "choice", options: Array<ChoiceOption>, } | { "type": "sensor" } | { "type": "channel" } | { "type": "curve" };
