// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

/**
 * One editable parameter of a node.
 */
export type ParamSpec = { 
/**
 * The serde field name on the node kind. Editing writes straight to it.
 */
key: string, label: string, 
/**
 * Shown beneath the control. Inline, never as hover text.
 */
help: string | null, kind: ParamKind, };
