// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantity } from "./Quantity";

/**
 * One typed port, as the editor sees it.
 */
export type PortDto = { key: string, label: string, quantity: Quantity, 
/**
 * A required input left unconnected makes the graph invalid.
 */
required: boolean, 
/**
 * A variadic input accepts any number of incoming connections.
 */
variadic: boolean, };
