// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";

/**
 * Identifies one port on one node. Port keys are stable strings owned by the node kind.
 */
export type PortRef = { node: NodeId, port: string, };
