// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantity } from "./Quantity";

/**
 * The inferred type of one port.
 */
export type PortTypeDto = { nodeId: string, port: string, 
/**
 * `None` when the port is generic and nothing has decided it yet.
 */
quantity: Quantity | null, };
