// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantity } from "./Quantity";

/**
 * A sensor the active backend can read.
 */
export type SensorDto = { id: string, label: string, quantity: Quantity, };
