// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireValue } from "./WireValue";

/**
 * The engine's most recent tick, as the editor sees it.
 */
export type SnapshotDto = { 
/**
 * Monotonic tick counter. Unchanged between reads means the loop has not ticked.
 */
sequence: bigint, 
/**
 * Seconds the last tick was evaluated over.
 */
dt: number, tickDurationMs: number, 
/**
 * Ticks that overran their period. Rising means the tick rate is too high.
 */
overruns: bigint, 
/**
 * True when no graph was evaluated and every channel was failsafed.
 */
degraded: boolean, 
/**
 * Why, when degraded because the sensors could not be read.
 */
sensorError: string | null, sensors: Array<WireValue>, wires: Array<WireValue>, 
/**
 * Duty actually written to each channel this tick.
 */
commanded: { [key in string]: number }, 
/**
 * Channels put into their failsafe this tick.
 */
failsafed: Array<string>, };
