// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentionReport } from "./ContentionReport";

/**
 * What a takeover attempt did.
 */
export type TakeoverResult = { 
/**
 * One line per thing attempted, in order, for the user to read.
 */
steps: Array<string>, succeeded: boolean, 
/**
 * Present when the attempt stopped early.
 */
blocker: string | null, 
/**
 * The situation afterwards.
 */
report: ContentionReport, };
