// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rejected graph edit.
 */
export type ValidationError = { 
/**
 * Human-readable, already explaining what to do about it.
 */
message: string, 
/**
 * The node to highlight, when the error names one.
 */
nodeId: string | null, };
