// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantity } from "./Quantity";

/**
 * One value on one wire, flattened for transport.
 *
 * `PortRef` is a struct and would be an awkward object key in JSON, so wire values
 * travel as a list the editor indexes by `nodeId`/`port`.
 */
export type WireValue = { nodeId: string, port: string, quantity: Quantity, 
/**
 * `None` when the value is not finite — a fault, not a number.
 */
value: number | null, };
