// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The physical quantity carried by a port, and therefore by a connection.
 */
export type Quantity = "temperature" | "duty" | "rpm" | "load" | "power" | "voltage" | "current" | "frequency" | "throughput" | "ratio" | "boolean" | "time";
