// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quantity } from "./Quantity";

/**
 * A quantity-tagged scalar: one value travelling along one connection.
 */
export type Value = { quantity: Quantity, 
/**
 * The magnitude, in the quantity's canonical unit.
 */
scalar: number, };
